version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./server/outputs:/app/outputs
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
